### PR TITLE
Add group_label into filed label [FRONT-5374]

### PR DESCRIPTION
**Pull request by nc-panx**
!! Please logic review!!

Need to do more test, but my theory behind this is:
I believe Docusign stopped supporting `CheckBox` some time ago, instead, adding a new checkbox will automatically be a `CheckBox Group` (it has a uneditable `group_label` associated with it).
Though there hasn't been any complex usage (we currently only have three CheckBox Group, and they're all for adding a single CheckBox), but we'll need to add `group_label` for CheckBox Group potential usage.
And this could also fix an error for this: https://github.com/BLC/rails/pull/12952#discussion_r667159737

### CODE REVIEW

**Comment by NC-piercej** [comment]
The fix is probably more complicated than this, but you're on the right track.

We'll need to make sure that:

1) Each checkbox in the group is checked/not checked correctly by the envelope generation code in AppServer
2) All checked boxes render correctly on the PDF via this repo

**Comment by NC-piercej** [comment]
Seems like checkbox tabs are merely associated with a group, which we can optionally apply behavior to ourselves. These changes may be sufficient, as long as checkboxes with associated checkbox groups work correctly.

**Comment by nc-panx** [comment]
I checked all the three usages (two JH forms and one TA to be added) of `CheckBox Group`, and they're still working.
If we're going to use more `CheckBox Group` rules, this may need more testing, but for now, they're all for a single checkbox without any `CheckBox Group` rules.

**Review by NC-piercej — APPROVED** [review]
🚀 There isn't Jenkins hookup here. You'll need to build the gem (via the rake task) and upload it to gems.nextcapital.com manually.

**Pull request merged**
